[package]
name = "varyk-syntax"
version = "0.0.2"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Lexer, parser, and AST for the Varyk programming language"
readme = "../../README.md"
keywords = ["varyk", "parser", "compiler"]
categories = ["parser-implementations", "compilers"]

[dependencies]
